<a href="https://colab.research.google.com/github/sathkumara-smna/258739K/blob/main/2G_3G_Eng_Rule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import pandas as pd

# Raw GitHub file URL
url = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/Site%20Database%20from%20Sey.xlsx"

# Load Excel file
df = pd.read_excel(url)

# Show first few rows
df.head(2)

,#,Site_ID,Site Name,2G RRUs,3G RRUs,4G RRUs,5G AAUs,2G Boards,3G Boards,4G Boards,5G Boards,BBU 5900,BBU 3900,BBU 3910
0,1,101,AIRPORT_MAHE,3,7,12,3,1,2,2,1,1,1,1
1,2,102,AIRPORT_PRASLIN,2,4,4,0,1,1,1,0,0,1,0

In [49]:
df.columns = [
    '#',
    'Site_ID',
    'Site_Name',
    'RRU_2G',
    'RRU_3G',
    'RRU_4G',
    'AAU_5G',
    'Col_H',
    'Col_I',
    'Boards_4G',
    'Boards_5G',
    'BBU5900',
    'BBU3900',
    'BBU3910'
]

In [50]:
# Create a new dataframe with only unique Site_IDs

df2g3g = df[['Site_ID']].drop_duplicates()

# Reset index
df2g3g = df2g3g.reset_index(drop=True)

# Show first rows
df2g3g.head(2)

   Site_ID
0      101
1      102

In [51]:
df2g3g['rru_count_2g'] = 0
df2g3g['rru_2g_bp'] = 150
df2g3g['power_2g'] = 0
df2g3g['rru_count_3g'] = 0
df2g3g['rru_3g_bp'] = 200
df2g3g['power_3g'] = 0
df2g3g['total_2g_3g_power'] = 0
# Show first rows
df2g3g.head(2)

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
0,101,0,150,0,0,200,0,0
1,102,0,150,0,0,200,0,0

In [52]:
# Fill rru_count_2g from df using Site_ID matching
df2g3g['rru_count_2g'] = (
        df2g3g['Site_ID'].map(
        df.set_index('Site_ID')['RRU_2G']
    )
)
# Show first rows
df2g3g.head()

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
0,101,3,150,0,0,200,0,0
1,102,2,150,0,0,200,0,0
2,103,3,150,0,0,200,0,0
3,104,2,150,0,0,200,0,0
4,105,2,150,0,0,200,0,0

In [53]:
# Calculate 2G power

df2g3g['power_2g'] = (
    df2g3g['rru_count_2g'] * df2g3g['rru_2g_bp']
)
# Show first rows
df2g3g.head(2)

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
0,101,3,150,450,0,200,0,0
1,102,2,150,300,0,200,0,0

In [54]:
# Fill rru_count_3g from df using Site_ID matching

df2g3g['rru_count_3g'] = (
        df2g3g['Site_ID'].map(
        df.set_index('Site_ID')['RRU_3G']
    )
)
# Show first rows
df2g3g.head()

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
0,101,3,150,450,7,200,0,0
1,102,2,150,300,4,200,0,0
2,103,3,150,450,6,200,0,0
3,104,2,150,300,2,200,0,0
4,105,2,150,300,4,200,0,0

In [55]:
# Calculate 3G power

df2g3g['power_3g'] = (df2g3g['rru_count_3g'] * df2g3g['rru_3g_bp'])
# Show first rows
df2g3g.head(2)

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
0,101,3,150,450,7,200,1400,0
1,102,2,150,300,4,200,800,0

In [56]:
# Show row for Site_ID = 163

df2g3g[df2g3g['Site_ID'] == 163]

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
59,163,0,150,0,6,200,1200,0

In [57]:
print(df2g3g.columns)

Index(['Site_ID', 'rru_count_2g', 'rru_2g_bp', 'power_2g', 'rru_count_3g',
       'rru_3g_bp', 'power_3g', 'total_2g_3g_power'],
      dtype='object')

In [58]:
# Calculate total 2G + 3G power

df2g3g['total_2g_3g_power'] = (
    df2g3g['power_2g'] + df2g3g['power_3g']
)
# Show first rows
df2g3g.head()

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
0,101,3,150,450,7,200,1400,1850
1,102,2,150,300,4,200,800,1100
2,103,3,150,450,6,200,1200,1650
3,104,2,150,300,2,200,400,700
4,105,2,150,300,4,200,800,1100

In [59]:
df2g3g.to_excel("site_power_2g3g.xlsx", index=False)